spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/myDB1
    driverClassName: org.h2.Driver
    username: sa1
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8081
